name: SketchDNN
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=py313h06a4308_0
  - alsa-lib=1.2.14=h5eee18b_0
  - aom=3.6.0=h6a678d5_0
  - asttokens=3.0.0=py313h06a4308_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - brotlicffi=1.0.9.2=py313h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py313h06a4308_0
  - comm=0.2.1=py313h06a4308_0
  - contourpy=1.3.1=py313hdb19cb5_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.16=py313hbdd6827_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py313h06a4308_0
  - executing=2.2.1=py313h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.17.0=py313h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py313h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - fsspec=2025.7.0=py313h7040dfc_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py313h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.71.0=py313h6a678d5_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - importlib-metadata=8.5.0=py313h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py313h06a4308_1
  - ipython=9.1.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jinja2=3.1.6=py313h06a4308_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=py313h06a4308_0
  - jupyter_core=5.8.1=py313h06a4308_0
  - kiwisolver=1.4.8=py313h6a678d5_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=13_h8e06fc2_netlib
  - libclang13=20.1.8=default_hee3e7a4_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcups=2.4.2=h252cb56_2
  - libcurand=10.3.5.147=h99ab3db_1
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.1.0=h767d61c_5
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=13_h8876d29_netlib
  - libllvm15=15.0.7=he89c38a_4
  - libllvm20=20.1.8=h465586c_0
  - libmpdec=4.0.0=h5eee18b_0
  - libnpp=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.6.0=cpu_mkl_h881e62d_106
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxkbfile=1.1.0=hf54ef8a_2
  - libxml2=2.13.8=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - libzlib=1.2.13=h4ab18f5_6
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=20.1.8=hc2b8361_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4=4.4.4=py313hdd09ace_1
  - lz4-c=1.10.0=h5888daf_1
  - markdown=3.8=py313h06a4308_0
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib=3.10.5=py313h78bf25f_0
  - matplotlib-base=3.10.5=py313he37261f_0
  - matplotlib-inline=0.1.6=py313h06a4308_0
  - mesalib=25.1.5=h31e3550_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py313h06a4308_0
  - mysql-common=9.3.0=h0021b1a_3
  - mysql-libs=9.3.0=h797a5cd_3
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - networkx=3.5=py313h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.11.0=py313hf08b387_0
  - numpy=2.3.1=py313h8d96ed3_0
  - numpy-base=2.3.1=py313h8e760e0_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=h8e75217_0
  - openssl=3.6.0=h26f9b46_0
  - opentelemetry-api=1.30.0=py313h06a4308_0
  - optree=0.14.1=py313hdb19cb5_0
  - packaging=25.0=py313h06a4308_0
  - pandas=2.3.2=py313h280b501_0
  - parso=0.8.4=py313h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py313h06a4308_0
  - pillow=11.3.0=py313hb1c3d2d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.7=py313h06a4308_0
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=5.29.3=py313he621ea3_0
  - psutil=7.0.0=py313hee96239_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py313h06a4308_0
  - pybind11=2.13.6=py313hdb19cb5_1
  - pybind11-global=2.13.6=py313hdb19cb5_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py313h06a4308_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pyside6=6.9.2=py313h2ddcaae_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.5=h4612cfd_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytorch=2.6.0=cpu_mkl_py313hfd6889d_106
  - pytorch-cuda=12.4=hc786d27_7
  - pytz=2025.2=py313h06a4308_0
  - pyzmq=26.2.0=py313h6a678d5_0
  - qtbase=6.9.1=h42f7b11_0
  - qtdeclarative=6.9.1=h0c31637_0
  - qtshadertools=6.9.1=h82d4f2e_0
  - qtsvg=6.9.1=h79b47f1_0
  - qttools=6.9.1=h10e1dd4_0
  - qtwebchannel=6.9.1=h82d4f2e_0
  - qtwebengine=6.9.1=hfb9d843_0
  - qtwebsockets=6.9.1=h82d4f2e_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.8.0=py313h06d4379_0
  - scipy=1.16.3=py313h11c21cd_1
  - setuptools=72.1.0=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - snappy=1.2.1=h6a678d5_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=py313h06a4308_0
  - sympy=1.14.0=py313h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py313h52d8a92_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h54e0aa7_0
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py313h06a4308_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313h06a4308_0
  - wcwidth=0.2.13=py313h06a4308_0
  - werkzeug=3.1.3=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - wrapt=1.17.0=py313h5eee18b_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=py313h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/devsathware/miniconda3/envs/SketchDNN
